# Generated by Django 6.0.4 on 2026-04-30 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParcelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('coverage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.TextField()),
                ('temples', models.TextField()),
                ('tourism', models.TextField()),
                ('industry', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RouteAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_city', models.CharField(max_length=100)),
                ('dest_city', models.CharField(max_length=100)),
                ('via_city', models.CharField(blank=True, max_length=100, null=True)),
                ('analysis_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban', models.BooleanField()),
                ('industrial', models.BooleanField()),
                ('pilgrimage', models.BooleanField()),
                ('transit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.IntegerField()),
                ('train', models.IntegerField()),
                ('private', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly', models.BigIntegerField()),
                ('daily', models.IntegerField()),
                ('festival', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='citydistance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='citydistance',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='citydistance',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.RemoveField(
            model_name='routedemanddistribution',
            name='route',
        ),
        migrations.RemoveField(
            model_name='routetransport',
            name='route',
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.RemoveField(
            model_name='transportschedule',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='transportschedule',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='population',
        ),
        migrations.RemoveField(
            model_name='route',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='route',
            name='source_city',
        ),
        migrations.RemoveField(
            model_name='route',
            name='via_city',
        ),
        migrations.AddField(
            model_name='city',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_distances', to='functions.city'),
        ),
        migrations.AddField(
            model_name='distance',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='distance',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_distances', to='functions.city'),
        ),
        migrations.AddField(
            model_name='parcelservice',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='population',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.city'),
        ),
        migrations.AddField(
            model_name='potential',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.city'),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.city'),
        ),
        migrations.AddField(
            model_name='suggestedroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='topvisitors',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.city'),
        ),
        migrations.AddField(
            model_name='topvisitors',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='transport',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='from_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_from', to='functions.city'),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.route'),
        ),
        migrations.AddField(
            model_name='transportdetail',
            name='to_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_to', to='functions.city'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.city'),
        ),
        migrations.DeleteModel(
            name='CityDistance',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='RouteDemandDistribution',
        ),
        migrations.DeleteModel(
            name='RouteTransport',
        ),
        migrations.DeleteModel(
            name='TransportSchedule',
        ),
    ]
