# Generated by Django 6.0.4 on 2026-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_distance_parcelservice_population_potential_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_text', models.CharField(max_length=255, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-search_count', '-updated_at'],
            },
        ),
    ]
