# Generated by Django 6.0.4 on 2026-04-29 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('bus_parcel', 'Bus Parcel'), ('train_parcel', 'Train Parcel'), ('courier', 'Courier'), ('taxi', 'Taxi')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('education', 'Education'), ('temple', 'Temple'), ('tourist', 'Tourist'), ('industry', 'Industry')], max_length=50)),
                ('yearly_visitors', models.BigIntegerField(default=0)),
                ('daily_visitors_normal', models.IntegerField(default=0)),
                ('daily_visitors_peak', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='functions.city')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destination', to='functions.city')),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_source', to='functions.city')),
                ('via_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_via', to='functions.city')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDemandDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('percentage', models.FloatField(default=0)),
                ('visitor_count', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_distributions', to='functions.route')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_percentage', models.FloatField(default=0)),
                ('train_percentage', models.FloatField(default=0)),
                ('car_percentage', models.FloatField(default=0)),
                ('taxi_percentage', models.FloatField(default=0)),
                ('flight_percentage', models.FloatField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='functions.route')),
            ],
        ),
        migrations.CreateModel(
            name='TransportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train')], max_length=10)),
                ('trips_per_day', models.IntegerField(default=0)),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_from', to='functions.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_to', to='functions.city')),
            ],
        ),
        migrations.CreateModel(
            name='CityDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.IntegerField()),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='functions.city')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='functions.city')),
            ],
            options={
                'unique_together': {('from_city', 'to_city')},
            },
        ),
    ]
